# -*- coding: utf-8 -*-
"""Steam_Game_Success_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17d9UNOM-ld6_2XJfbiERPhtF1xPL8wRt
"""

# ================================
# STEAM SUCCESS ML PIPELINE (FIXED FOR YOUR DATASET)
# ================================

import sys
sys.path.insert(0, "/content/src")

import pandas as pd
import numpy as np

from data_preprocessing import load_and_clean_data
from feature_engineering import tfidf_features
from clustering import create_clusters
from train_models import train_models

# ------------------------
# STEP 1 — Load data
# ------------------------
print("Step 1 — Loading data")
# Load RAW data first
raw_df = pd.read_csv("/content/steam.csv")

# Then clean it
df = load_and_clean_data("/content/steam.csv")

print("Columns:", df.columns.tolist())

# ------------------------
# STEP 2 — Choose TEXT column (IMPORTANT FIX)
# ------------------------
TEXT_COL = "steamspy_tags"  # BEST choice for clustering games

df[TEXT_COL] = df[TEXT_COL].fillna("")

# ------------------------
# STEP 3 — TF-IDF
# ------------------------
print("Step 2 — TF-IDF feature extraction")

tfidf_matrix, tfidf_vectorizer = tfidf_features(df[TEXT_COL])

print("TF-IDF shape:", tfidf_matrix.shape)

# ------------------------
# STEP 4 — Clustering
# ------------------------
print("Step 3 — Clustering")

clusters = create_clusters(tfidf_matrix)

# SAFETY CHECK (prevents your earlier bug)
assert len(clusters) == len(df), \
    f"Cluster mismatch: {len(clusters)} vs {len(df)}"

df["cluster"] = clusters

# ------------------------
# STEP 5 — Feature engineering
# ------------------------
print("Step 4 — Building ML dataset")

# Target: success = more positive than median
df["success"] = (
    df["positive_ratings"] > df["positive_ratings"].median()
).astype(int)

# Fix owners (string range → number)
df["owners"] = (
    df["owners"]
    .astype(str)
    .str.split("-")
    .str[0]
    .str.replace(",", "")
    .astype(int)
)

# Fix price column typo if needed
if "pric" in df.columns:
    df["price"] = df["pric"]
elif "price" not in df.columns:
    df["price"] = 0

# ------------------------
# STEP 6 — Feature set
# ------------------------
feature_cols = [
    "price",
    "achievements",
    "average_playtime",
    "median_playtime",
    "owners",
    "cluster"
]

X = df[feature_cols].fillna(0)
y = df["success"]

print("Feature matrix shape:", X.shape)

# ------------------------
# STEP 7 — Train model
# ------------------------
print("Step 5 — Training models")

trained_models, X_test, y_test = train_models(X, y)

print("🎉 PIPELINE COMPLETE 🎉")

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

from sklearn.decomposition import PCA
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

import matplotlib.pyplot as plt

plt.rcParams["figure.figsize"] = (8,5)     # smaller figures
plt.rcParams["xtick.labelsize"] = 8        # smaller x labels
plt.rcParams["ytick.labelsize"] = 8
plt.rcParams["axes.titlesize"] = 12

plt.xticks(rotation=45, ha="right")
plt.tight_layout()

plt.figure()
df["success"].value_counts().plot(kind="bar")
plt.title("Distribution of Successful vs Non-Successful Steam Games")
plt.ylabel("Number of Games")
plt.xticks(rotation=0)
plt.show()

import seaborn as sns

plt.figure(figsize=(10,8))
sns.heatmap(df.corr(numeric_only=True))
plt.title("Correlation Between Numerical Features")
plt.show()

from sklearn.preprocessing import StandardScaler

# Features used for clustering / PCA
feature_cols = [
    "price",
    "achievements",
    "average_playtime",
    "median_playtime",
    "owners",
    "cluster"
]

X = df[feature_cols]

# Standardize features (very important for PCA)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

plt.figure(figsize=(8,6))
plt.scatter(X_pca[:,0], X_pca[:,1], c=df["cluster"])
plt.title("K-Means Market Segments of Steam Games")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

models = {
    "Logistic Regression": LogisticRegression(max_iter=2000),
    "Random Forest": RandomForestClassifier(n_estimators=200, random_state=42),
    "XGBoost": XGBClassifier(eval_metric="logloss")
}

results = {}
trained_models = {}

for name, model in models.items():
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    probs = model.predict_proba(X_test)[:,1]

    results[name] = {
        "accuracy": accuracy_score(y_test, preds),
        "precision": precision_score(y_test, preds),
        "recall": recall_score(y_test, preds),
        "f1": f1_score(y_test, preds),
        "roc_auc": roc_auc_score(y_test, probs)
    }

    trained_models[name] = model

# Save best model for ROC plot later
rf_model = trained_models["Random Forest"]

print(pd.DataFrame(results).T)

results_df = pd.DataFrame(results).T

plt.figure(figsize=(8,6))
results_df[["accuracy","f1","roc_auc"]].plot(kind="bar")
plt.title("Performance Comparison of ML Models")
plt.xticks(rotation=0)
plt.ylabel("Score")
plt.show()

from sklearn.metrics import RocCurveDisplay

plt.figure()
RocCurveDisplay.from_estimator(rf_model, X_test, y_test)
plt.title("ROC Curve — Random Forest")
plt.show()

import matplotlib.pyplot as plt
from matplotlib.ticker import ScalarFormatter

label_map = {
    "price": "Price",
    "owners": "Owners",
    "average_playtime": "Average Playtime"
}

fig, axes = plt.subplots(1, 3, figsize=(15,4))  # 1 row, 3 columns

for ax, col in zip(axes, numeric_cols):
    upper = df[col].quantile(0.99)
    data = df[df[col] <= upper][col]

    ax.hist(data, bins=50)

    pretty_name = label_map[col]
    ax.set_title(pretty_name)
    ax.set_xlabel(pretty_name)
    ax.set_ylabel("Number of Games")

    ax.xaxis.set_major_formatter(ScalarFormatter())
    ax.ticklabel_format(style='plain', axis='x')

plt.tight_layout()
plt.savefig("numeric_distributions.png")
plt.show()

plt.figure(figsize=(6,4))
df["success"].value_counts().plot(kind="bar")

plt.title("Distribution of Successful vs Unsuccessful Games")
plt.xlabel("Success Label")
plt.ylabel("Number of Games")
plt.xticks(rotation=0)

plt.tight_layout()
plt.savefig("target_distribution.png")
plt.show()

import numpy as np

feature_names = tfidf_vectorizer.get_feature_names_out()
scores = np.asarray(tfidf_matrix.mean(axis=0)).ravel()

top_n = 20
top_idx = scores.argsort()[-top_n:]

plt.figure(figsize=(8,5))
plt.barh(range(top_n), scores[top_idx])
plt.yticks(range(top_n), feature_names[top_idx])
plt.title("Top TF-IDF Terms in Game Descriptions")
plt.xlabel("Average TF-IDF Score")

plt.tight_layout()
plt.savefig("tfidf_features.png")
plt.show()

from sklearn.decomposition import PCA

pca = PCA(n_components=2)
X_pca = pca.fit_transform(tfidf_matrix.toarray())

plt.figure(figsize=(6,5))
plt.scatter(X_pca[:,0], X_pca[:,1], c=clusters, s=5)

plt.title("Market Segments from PCA + K-Means")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")

plt.tight_layout()
plt.savefig("pca_clusters.png")
plt.show()

import pandas as pd

results_df = pd.DataFrame(results).T

plt.figure(figsize=(7,5))
results_df[["accuracy","f1","roc_auc"]].plot(kind="bar")

plt.title("Performance Comparison of ML Models")
plt.ylabel("Score")
plt.xticks(rotation=0)

plt.tight_layout()
plt.savefig("model_comparison.png")
plt.show()